---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trillium-next
  namespace: home
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: trillium-next
    template:
      engineVersion: v2
      data:
        TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHCLIENTID: "{{ .client_id }}"
        TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHCLIENTSECRET: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: zitadel-trillium-next-oidc
