---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mondoo-client
  namespace: mondoo-operator
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mondoo-client
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config: "{{ .MONDOO_CONFIG_JSON }}"
  dataFrom:
    - extract:
        key: mondoo
