---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name immich-green
  namespace: home
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 18
  instances: 2
  primaryUpdateStrategy: unsupervised
  enablePDB: true
  storage:
    size: 10Gi
    storageClass: openebs-hostpath
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db
  enableSuperuserAccess: true
  superuserSecret:
    name: immich-db-superuser
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 256MB
      wal_level: logical
      max_replication_slots: "10"
      max_wal_senders: "10"
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: immich-rustfs-store
        serverName: immich-green
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
