---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: redis-auth
    template:
      engineVersion: v2
      data:
        admin_password: "{{ .admin_password }}"
        users.acl: |-
          user default on #{{ .admin_password | sha256sum }} ~* &* +@all
          user paperless on #{{ .paperless_password | sha256sum }} ~* &* +@read +@write +@connection +@transaction +@pubsub +@scripting -@admin -@dangerous +info +client|setname +client|setinfo +client|id +client|unblock
          user n8n on #{{ .n8n_password | sha256sum }} ~* &* +@read +@write +@connection +@transaction +@pubsub +@scripting -@admin -@dangerous +info +client|setname +client|setinfo +client|id +client|unblock
          user penpot on #{{ .penpot_password | sha256sum }} ~* &* +@read +@write +@connection +@transaction +@pubsub +@scripting -@admin -@dangerous +info +client|setname +client|setinfo +client|id +client|unblock
  dataFrom:
    - extract:
        key: redis-auth
