---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: redis-ingress
  namespace: database
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: master
      app.kubernetes.io/instance: redis
      app.kubernetes.io/name: redis
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: home-automation
            k8s:app.kubernetes.io/instance: n8n
            k8s:app.kubernetes.io/name: n8n
      toPorts:
        - ports:
            - port: "6379"
              protocol: TCP
