---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name rustfs-credentials
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        RUSTFS_ACCESS_KEY: "{{ .username }}"
        RUSTFS_SECRET_KEY: "{{ .password }}"
  dataFrom:
    - extract:
        key: rustfs
