# yaml-language-server: $schema=https://demo.frigate.video/api/config/schema.json
---
logger:
  default: info

mqtt:
  host: mosquitto.home-automation.svc.cluster.local
  topic_prefix: frigate

database:
  path: /data/frigate.db

detectors:
  rknn:
    type: rknn
    num_cores: 3

model:
  path: frigate-fp16-yolov9-t
  model_type: yolo-generic
  width: 320
  height: 320
  input_tensor: nhwc
  labelmap_path: /labelmap/coco-80.txt

# https://docs.frigate.video/configuration/hardware_acceleration_video#rockchip-platform
ffmpeg:
  hwaccel_args: preset-rkmpp
  apple_compatibility: true

record:
  enabled: true
  continuous:
    days: 0
  motion:
    days: 7

snapshots:
  enabled: true
  retain:
    default: 30

objects:
  track: ["bird"]

go2rtc:
  streams:
    birdy:
      - rtsp://192.168.1.180:8554/main
      - "ffmpeg:birdy#audio=aac"
      - "ffmpeg:birdy#audio=opus"
    birdy_sub:
      - rtsp://192.168.1.180:8554/sub

cameras:
  birdy:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/birdy
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/birdy_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    live:
      streams:
        Main: birdy
        Sub: birdy_sub
    objects:
      filters:
        bird: {}
    notifications:
      enabled: true
    zones:
      Nesting:
        coordinates: 0.218,0.935,0.249,0.381,0.717,0.383,0.803,0.952
        loitering_time: 5
    review:
      alerts:
        required_zones: Nesting

detect:
  enabled: true

version: 0.17-0

semantic_search:
  enabled: true
  model_size: small

face_recognition:
  enabled: false
  model_size: small

lpr:
  enabled: false

classification:
  bird:
    enabled: true

notifications:
  enabled: false
  email: dan.m.webb@gmail.com
