---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate-mqtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-mqtt
    creationPolicy: Owner
  data:
    - secretKey: FRIGATE_MQTT_PASSWORD
      remoteRef:
        key: mqtt-auth
        property: frigate_password
