---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-db
  namespace: authentication
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zitadel-db
    template:
      engineVersion: v2
      data:
        username: "zitadel"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: zitadel-db
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-db-superuser
  namespace: authentication
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zitadel-db-superuser
    template:
      engineVersion: v2
      data:
        username: postgres
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: zitadel-db-superuser
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-cnpg-zitadel
  namespace: authentication
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rustfs-cnpg-zitadel
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        ACCESS_KEY_ID: "{{ .username }}"
        SECRET_ACCESS_KEY: "{{ .password }}"
  dataFrom:
    - extract:
        key: rustfs-cnpg-zitadel
