---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
# App secret key (used to sign sessions)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: penpot-secret
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: penpot-secret
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: penpot
        property: api_secret_key
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
# Zitadel OIDC credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: penpot-zitadel-oidc
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: penpot-zitadel-oidc
    template:
      engineVersion: v2
      type: Opaque
      data:
        client-id: "{{ .client_id }}"
        client-secret: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: zitadel-penpot-oidc
