---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: penpot-assets
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 20Gi
