---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: penpot-redis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: penpot-redis
    template:
      engineVersion: v2
      data:
        uri: "redis://penpot:{{ .password }}@redis-master.database.svc.cluster.local:6379/3"
  data:
    - secretKey: password
      remoteRef:
        key: redis-auth
        property: penpot_password
