tap 'fluxcd/tap'
tap 'home-operations/tap'
tap 'mondoohq/mondoo'

brew 'age'
brew 'cloudflared'
brew 'cnspec'
brew 'direnv'
brew 'fluxcd/tap/flux'
brew 'helm'
brew 'helmfile'
brew 'jq'
brew 'kubernetes-cli'
brew 'kustomize'
brew 'moreutils'
brew 'mondoohq/mondoo/cnspec'
brew 'sops'
brew 'stern'
brew 'yq'

cask 'home-operations/tap/flate'
cask 'home-operations/tap/yayamlls'
