[tools]
go = "1.26.6"
python = "3.14.7"
shellcheck = "0.11.0"
yq = "4.53.3"
jq = "1.8.2"
kubectl = "1.36.3"
helm = "4.2.4"
task = "3.52.0"
gh = "2.97.0"
sops = "3.13.3"
kustomize = "5.8.1"

[settings]
auto_install = false
