---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-cnpg-penpot
  namespace: home
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rustfs-cnpg-penpot
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        ACCESS_KEY_ID: "{{ .username }}"
        SECRET_ACCESS_KEY: "{{ .password }}"
  dataFrom:
    - extract:
        key: rustfs-cnpg-penpot
