---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: med-tracker-canary-secret
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: med-tracker-canary-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        DATABASE_URL: "postgresql://med-tracker:{{ .db_password | urlquery
          }}@med-tracker-canary-rw.home.svc.cluster.local:5432/med-tracker"
        SOLID_CACHE_DATABASE_URL: "postgresql://med-tracker:{{ .db_password | urlquery
          }}@med-tracker-canary-rw.home.svc.cluster.local:5432/medtracker_pro\
          duction_cache"
        SOLID_QUEUE_DATABASE_URL: "postgresql://med-tracker:{{ .db_password | urlquery
          }}@med-tracker-canary-rw.home.svc.cluster.local:5432/medtracker_pro\
          duction_queue"
        SOLID_CABLE_DATABASE_URL: "postgresql://med-tracker:{{ .db_password | urlquery
          }}@med-tracker-canary-rw.home.svc.cluster.local:5432/medtracker_pro\
          duction_cable"
        OIDC_CLIENT_ID: "{{ .client_id }}"
        OIDC_CLIENT_SECRET: "{{ .client_secret }}"
        SMTP_ADDRESS: "smtp.resend.com"
        SMTP_USER_NAME: "resend"
        SMTP_PASSWORD: "{{ .RESEND_API_KEY }}"
        MAILER_FROM: "MedTracker Canary <notifications+canary@damacus.io>"
  dataFrom:
    - extract:
        key: med-tracker-canary
    - extract:
        key: zitadel-med-tracker-canary-oidc
  data:
    - secretKey: db_password
      remoteRef:
        key: med-tracker-canary-db
        property: password
