---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - helmrelease.yaml
  - externalsecret.yaml
  - grafana-dashboard.yaml
  - networkpolicy.yaml
  - reset-rbac.yaml
  - reset-script.yaml
  - storage-pvc.yaml
