---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot-config
  namespace: dev
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zot-config
    template:
      engineVersion: v2
      data:
        config.json: |-
          {
            "distSpecVersion": "1.1.1",
            "storage": {
              "rootDirectory": "/var/lib/zot",
              "dedupe": false,
              "gc": false,
              "redirectBlobURL": false,
              "storageDriver": {
                "name": "s3",
                "rootdirectory": "/zot",
                "region": "us-east-1",
                "bucket": "cinc-registry-oci",
                "regionendpoint": "http://rustfs.storage.svc.cluster.local:9000",
                "forcepathstyle": true,
                "secure": false,
                "skipverify": false,
                "accesskey": {{ .access_key | toJson }},
                "secretkey": {{ .secret_key | toJson }}
              }
            },
            "http": {
              "address": "0.0.0.0",
              "port": "5000",
              "auth": {
                "bearer": {
                  "realm": "https://cinc-registry.ironstone.casa/api/v2/oci/token",
                  "service": "cinc-registry",
                  "cert": "/etc/zot/token.crt"
                }
              }
            },
            "log": {
              "level": "info"
            }
          }
        token.crt: "{{ .certificate }}"
  data:
  - secretKey: access_key
    remoteRef:
      key: rustfs-cinc-registry-oci
      property: username
  - secretKey: secret_key
    remoteRef:
      key: rustfs-cinc-registry-oci
      property: password
  - secretKey: certificate
    remoteRef:
      key: cinc-registry-oci-signing
      property: certificate
