---
apiVersion: postgresql.cnpg.io/v1
kind: Publication
metadata:
  name: immich-green-pub
  namespace: home
spec:
  cluster:
    name: immich
  dbname: immich
  name: immich_green_pub
  publicationReclaimPolicy: delete
  target:
    allTables: true
