---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: alertmanager-secret
    template:
      engineVersion: v2
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          route:
            group_by: ["alertname", "job"]
            group_interval: 10m
            group_wait: 1m
            receiver: oncall
            repeat_interval: 12h
            routes:
              - receiver: heartbeat
                group_interval: 5m
                group_wait: 0s
                matchers:
                  - alertname=~"Watchdog"
                repeat_interval: 5m
              - receiver: "null"
                matchers:
                  - alertname=~"InfoInhibitor"
              - receiver: oncall-critical
                matchers:
                  - severity="critical"
              - receiver: oncall
                mute_time_intervals:
                  - weekday-evenings
                  - weekends
                matchers:
                  - severity=~"warning|info"
          time_intervals:
            - name: weekday-evenings
              time_intervals:
                - times:
                    - start_time: "18:00"
                      end_time: "23:59"
                  weekdays: ["monday:friday"]
                - times:
                    - start_time: "00:00"
                      end_time: "08:00"
                  weekdays: ["tuesday:saturday"]
            - name: weekends
              time_intervals:
                - times:
                    - start_time: "18:00"
                      end_time: "23:59"
                  weekdays: ["friday"]
                - weekdays: ["saturday", "sunday"]
                - times:
                    - start_time: "00:00"
                      end_time: "08:00"
                  weekdays: ["monday"]
          inhibit_rules:
            - equal: ["alertname", "namespace"]
              source_matchers:
                - severity="critical"
              target_matchers:
                - severity="warning"
          receivers:
            - name: heartbeat
              webhook_configs:
                - send_resolved: false
                  url: "http://gatus.monitoring.svc.cluster.local:8080/api/v1/endpoints/cluster_alertmanager-watchdog/external?success=true"
                  http_config:
                    authorization:
                      credentials: "{{ .GATUS_WATCHDOG_TOKEN }}"
            - name: "null"
            - name: oncall
              webhook_configs:
                - send_resolved: true
                  max_alerts: 100
                  url: "{{ .GRAFANA_ONCALL_ALERTMANAGER_URL }}"
            - name: oncall-critical
              webhook_configs:
                - send_resolved: true
                  max_alerts: 100
                  url: "{{ .GRAFANA_ONCALL_ALERTMANAGER_URL }}"
  dataFrom:
    - extract:
        key: alertmanager
    - extract:
        key: gatus
  data:
    - secretKey: GRAFANA_ONCALL_ALERTMANAGER_URL
      remoteRef:
        key: grafana-cloud-oncall
        property: GRAFANA_ONCALL_ALERTMANAGER_URL
