---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 1h
  timeout: 60s
  url: https://github.com/kubernetes-sigs/gateway-api.git
  ref:
    tag: v1.6.1
