---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mosquitto-auth
    creationPolicy: Owner
  data:
    - secretKey: password_file
      remoteRef:
        key: mqtt-auth
        property: password_file
