persistence true
persistence_location /data/mosquitto/
listener 1883
allow_anonymous false
password_file /mosquitto/auth/password_file
acl_file /mosquitto/config/acl.conf
per_listener_settings false
connection_messages true
autosave_interval 60
