---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-northops-postgres
  namespace: storage
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rustfs-northops-postgres
    template:
      engineVersion: v2
      data:
        RUSTFS_NORTHOPS_POSTGRES_ACCESS_KEY: "{{ .username }}"
        RUSTFS_NORTHOPS_POSTGRES_SECRET_KEY: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: rustfs-cnpg-northops-postgres
        property: username
    - secretKey: password
      remoteRef:
        key: rustfs-cnpg-northops-postgres
        property: password
