---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &oncall grafana-oncall-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *oncall
    template:
      engineVersion: v2
      data:
        GF_PLUGIN_GRAFANA_ONCALL_APP_ONCALL_API_URL: "https://oncall-prod-eu-west-0.grafana.net/oncall"
        GF_PLUGIN_GRAFANA_ONCALL_APP_ONCALL_TOKEN: "{{ .GRAFANA_ONCALL_TOKEN }}"
  data:
    - secretKey: GRAFANA_ONCALL_TOKEN
      remoteRef:
        key: grafana-cloud-oncall
        property: credential
