---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 10.1.0@sha256:b02b4687b11570f82c8bc9967556f782efaa9bf0422b39b5b2a1b0c2203f3cb3
  url: oci://ghcr.io/grafana/helm-charts/grafana
