#!/usr/bin/env bash
#MISE description="Check the certificates"
#MISE quiet=true
#MISE raw=true
set -euo pipefail

cd certificates
openssl x509 -in ironstone-casa-tls.crt -noout -checkend 86400
openssl rsa -in ironstone-casa-tls.key -noout -check
