#!/usr/bin/env bash
#MISE description="Generate the Unifi keystore"
#MISE quiet=true
#MISE raw=true
set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../../.." >/dev/null 2>&1 && pwd)"
cd "${repo_root}/certificates"
exec openssl pkcs12 -export -in ironstone-casa-tls.crt -inkey ironstone-casa-tls.key -out ironstone-keystore.p12 -name unifi
