---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./servicemonitor.yaml
  - ./networkpolicy.yaml
  - ./grafana-alerts.yaml
  - ./grafana-dashboard.yaml
