---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/publication_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Publication
metadata:
  name: home-assistant-green-pub
  namespace: home-automation
spec:
  cluster:
    name: home-assistant
  dbname: app
  name: home_assistant_green_pub
  publicationReclaimPolicy: delete
  target:
    allTables: true
