---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/subscription_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Subscription
metadata:
  name: home-assistant-green-sub
  namespace: home-automation
spec:
  cluster:
    name: home-assistant-green
  dbname: app
  name: home_assistant_green_sub
  publicationName: home_assistant_green_pub
  externalClusterName: home-assistant
  subscriptionReclaimPolicy: delete
