---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: patchbotmcbotface-github-app
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: patchbotmcbotface-github-app
    template:
      data:
        githubAppID: "{{ .PATCHBOT_GITHUB_APP_ID }}"
        githubAppInstallationID: "{{ .PATCHBOT_GITHUB_APP_INSTALLATION_ID }}"
        githubAppPrivateKey: "{{ .PATCHBOT_GITHUB_APP_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: flux
