---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ironbridge-db
  namespace: dev
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ironbridge-db
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: kubernetes.io/basic-auth
      data:
        username: ironbridge
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: ironbridge-db
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-cnpg-northops
  namespace: dev
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rustfs-cnpg-northops
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        ACCESS_KEY_ID: "{{ .username }}"
        SECRET_ACCESS_KEY: "{{ .password }}"
  dataFrom:
    - extract:
        key: rustfs-cnpg-northops
