---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name med-tracker
  namespace: home
spec:
  imagePullSecrets:
    - name: ghcr-credentials
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 18
  instances: 2
  primaryUpdateStrategy: unsupervised
  managed:
    roles:
      - name: med_tracker_audit_exporter
        ensure: present
        login: false
        superuser: false
        bypassrls: false
      - name: med_tracker_audit_verifier
        ensure: present
        login: false
        superuser: false
        bypassrls: false
  storage:
    size: 5Gi
    storageClass: openebs-hostpath

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: *name
      owner: *name
      secret:
        name: med-tracker-db

  enableSuperuserAccess: true
  superuserSecret:
    name: med-tracker-db-superuser

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 128MB

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: med-tracker-rustfs-store
        serverName: med-tracker

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 2000m
      memory: 512Mi
