---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: med-tracker-db
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: med-tracker-db
    template:
      data:
        username: "med-tracker"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: med-tracker-db
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: med-tracker-db-superuser
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: med-tracker-db-superuser
    template:
      data:
        username: "postgres"
        password: "{{ .superuser_password }}"
  dataFrom:
    - extract:
        key: med-tracker-db
        property: superuser_password
