---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: med-tracker-db
  namespace: home
spec:
  schedule: "0 40 3 * * *"
  immediate: true
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      objectStore: med-tracker-rustfs-store
  cluster:
    name: med-tracker
