#!/usr/bin/env bash
#MISE description="Check all ExternalSecrets have synchronized successfully"
#MISE quiet=true
#MISE raw=true
set -euo pipefail
exec task "kubernetes:external-secrets-health" -- "$@"
