#!/usr/bin/env bash
#MISE description="Report Cilium health"
#MISE quiet=true
#MISE raw=true
#MISE depends=["kubernetes:cluster-health-build"]
set -euo pipefail
exec .cache/bin/cluster-health cilium "$@"
