#!/usr/bin/env bash
#MISE description="Gather common resources in your cluster, useful when asking for support"
#MISE quiet=true
#MISE raw=true
set -euo pipefail

args=("$@")
[ "${#args[@]}" -gt 0 ] || args=(-A)
for resource in nodes gitrepositories kustomizations helmrepositories helmreleases certificates certificaterequests ingresses pods; do
  kubectl get "$resource" "${args[@]}"
done
