#!/usr/bin/env bash
#MISE description="Gather common resources in your cluster, useful when asking for support"
#MISE quiet=true
#MISE raw=true
set -euo pipefail
exec task "kubernetes:resources" -- "$@"
