---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: med-tracker-dmd-import-env
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: med-tracker-dmd-import-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .username }}"
        AWS_SECRET_ACCESS_KEY: "{{ .password }}"
        AWS_DEFAULT_REGION: us-east-1
        AWS_EC2_METADATA_DISABLED: "true"
        AWS_ENDPOINT_URL_S3: http://minio.storage.svc.cluster.local:9000
        DMD_RELEASE_URI: s3://med-tracker/nhs-dmd/releases/2026-04-12/current/
  dataFrom:
    - extract:
        key: minio-cnpg
