---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: med-tracker-secret
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: med-tracker-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        DATABASE_URL: "postgresql://med-tracker:{{ .db_password
          }}@med-tracker-rw.home.svc.cluster.local:5432/med-tracker"
        SOLID_CACHE_DATABASE_URL: "postgresql://med-tracker:{{ .db_password
          }}@med-tracker-rw.home.svc.cluster.local:5432/medtracker_production_c\
          ache"
        SOLID_QUEUE_DATABASE_URL: "postgresql://med-tracker:{{ .db_password
          }}@med-tracker-rw.home.svc.cluster.local:5432/medtracker_production_q\
          ueue"
        SOLID_CABLE_DATABASE_URL: "postgresql://med-tracker:{{ .db_password
          }}@med-tracker-rw.home.svc.cluster.local:5432/medtracker_production_c\
          able"
        OIDC_CLIENT_ID: "{{ .client_id }}"
        OIDC_CLIENT_SECRET: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: med-tracker
    - extract:
        key: zitadel-med-tracker-oidc
  data:
    - secretKey: db_password
      remoteRef:
        key: med-tracker-db
        property: password
