---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./immich-db/ks.yaml
  - ./mealie-db/ks.yaml
  - ./mealie/ks.yaml
  - ./memos/ks.yaml
  - ./med-tracker-db/ks.yaml
  - ./med-tracker/ks.yaml
  - ./namespace.yaml
