---
apiVersion: postgresql.cnpg.io/v1
kind: Publication
metadata:
  name: forgejo-green-pub
  namespace: dev
spec:
  cluster:
    name: forgejo
  dbname: forgejo
  name: forgejo_green_pub
  publicationReclaimPolicy: delete
  target:
    allTables: true
