---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  CERTS_DIR: "certificates"

tasks:
  download-certificates:
    desc: Download the certificates from the cluster
    dir: "{{.CERTS_DIR}}"
    cmds:
      - cmd: kubectl get secrets -n network ironstone-casa-production-tls -o yaml | yq -r '.data."tls.crt"' | base64 -d > ironstone-casa-tls.crt
      - cmd: kubectl get secrets -n network ironstone-casa-production-tls -o yaml | yq -r '.data."tls.key"' | base64 -d > ironstone-casa-tls.key
      - task: check-certificates

  check-certificates:
    desc: Check the certificates
    dir: "{{.CERTS_DIR}}"
    cmds:
      - cmd: openssl x509 -in ironstone-casa-tls.crt -noout -checkend 86400
      - cmd: openssl rsa -in ironstone-casa-tls.key -noout -check
