---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tempo-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tempo-secret
    template:
      engineVersion: v2
      data:
        RUSTFS_TEMPO_ACCESS_KEY: "{{ .username }}"
        RUSTFS_TEMPO_SECRET_KEY: "{{ .password }}"
  dataFrom:
    - extract:
        key: rustfs-tempo
