---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: forgejo-admin
  dataFrom:
    - extract:
        key: forgejo
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-zitadel-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: forgejo-zitadel-oidc
    template:
      engineVersion: v2
      data:
        key: "{{ .client_id }}"
        secret: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: zitadel-forgejo-oidc
