---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-cnpg-northops
  namespace: storage
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rustfs-cnpg-northops
    template:
      engineVersion: v2
      data:
        RUSTFS_CNPG_NORTHOPS_ACCESS_KEY: "{{ .username }}"
        RUSTFS_CNPG_NORTHOPS_SECRET_KEY: "{{ .password }}"
  dataFrom:
    - extract:
        key: rustfs-cnpg-northops
