---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/publication_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Publication
metadata:
  name: mealie-green-pub
  namespace: home
spec:
  cluster:
    name: mealie
  dbname: mealie
  name: mealie_green_pub
  publicationReclaimPolicy: delete
  target:
    allTables: true
