---
apiVersion: postgresql.cnpg.io/v1
kind: Publication
metadata:
  name: mealie-green-pub
  namespace: home
spec:
  cluster:
    name: mealie
  dbname: mealie
  name: mealie_green_pub
  publicationReclaimPolicy: delete
  target:
    allTables: true
