---
apiVersion: postgresql.cnpg.io/v1
kind: Subscription
metadata:
  name: mealie-green-sub
  namespace: home
spec:
  cluster:
    name: mealie-green
  dbname: mealie
  name: mealie_green_sub
  publicationName: mealie_green_pub
  externalClusterName: mealie
  subscriptionReclaimPolicy: delete
