---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cinc-registry-db-owner
  namespace: dev
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cinc-registry-db-owner
    template:
      engineVersion: v2
      data:
        username: cinc_sm_owner
        password: "{{ .password }}"
      type: kubernetes.io/basic-auth
  data:
  - secretKey: password
    remoteRef:
      key: cinc-registry-db-owner
      property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cinc-registry-db-runtime
  namespace: dev
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cinc-registry-db-runtime
    template:
      engineVersion: v2
      data:
        username: cinc_sm_runtime
        password: "{{ .password }}"
      type: kubernetes.io/basic-auth
  data:
  - secretKey: password
    remoteRef:
      key: cinc-registry-db-runtime
      property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-cnpg-cinc-registry
  namespace: dev
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rustfs-cnpg-cinc-registry
    template:
      engineVersion: v2
      data:
        ACCESS_KEY_ID: "{{ .username }}"
        SECRET_ACCESS_KEY: "{{ .password }}"
  data:
  - secretKey: username
    remoteRef:
      key: rustfs-cnpg-cinc-registry
      property: username
  - secretKey: password
    remoteRef:
      key: rustfs-cnpg-cinc-registry
      property: password
