---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-localdata-restore
  namespace: home-automation
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 6Gi
  storageClassName: longhorn
