---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-redis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-redis
    template:
      engineVersion: v2
      data:
        uri: "redis://paperless:{{ .password }}@redis-master.database.svc.cluster.local:6379/0"
  data:
    - secretKey: password
      remoteRef:
        key: redis-auth
        property: paperless_password
