---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: forgejo-runner
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        runner-config.yml: |
          log:
            level: info
            job_level: info

          runner:
            file: /home/runner/.runner
            capacity: 1
            envs:
              STORAGE_DRIVER: vfs
              BUILDAH_ISOLATION: chroot
              XDG_RUNTIME_DIR: /tmp/run
            timeout: 3h
            shutdown_timeout: 3h
            insecure: false
            fetch_timeout: 30s
            fetch_interval: 2s
            report_interval: 1s
            labels:
              - self-hosted:host
              - linux-arm64:host
              - buildah:host

          cache:
            enabled: false

          container:
            privileged: false
            options:
            valid_volumes: []
            docker_host: "-"

          host:
            workdir_parent: /home/runner/work

          server:
            connections:
              forgejo:
                url: http://forgejo-http.dev.svc.cluster.local:3000/
                uuid: "{{ .uuid }}"
                token: "{{ .token }}"
  data:
    - secretKey: uuid
      remoteRef:
        key: forgejo-runner
        property: uuid
    - secretKey: token
      remoteRef:
        key: forgejo-runner
        property: token
