---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rustfs-iam-northops
  namespace: flux-system
spec:
  targetNamespace: storage
  commonMetadata:
    labels:
      app.kubernetes.io/name: rustfs-iam
  dependsOn:
    - name: rustfs-iam
    - name: external-secrets-stores
  path: ./kubernetes/apps/storage/rustfs-iam/northops
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: true
