{
 "title": "Uptime-Kuma Status",
 "description": "A simple dashboard showcasing service status updates over time tracked by the Uptime Kuma monitoring tool.",
 "tags": [
  "uptime-kuma",
  "metrics"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "Instance", "query": { "query": "query_result(monitor_status)" } },
   { "name": "monitor_types", "label": "Monitor Type", "query": { "query": "label_values(monitor_type)" } },
   {
    "name": "groups",
    "label": "Groups",
    "query": {
     "query": "label_values({monitor_type=\"group\"},monitor_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(instance) (monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type!=\"group\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count by(instance) (monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type!=\"group\"} == 1)",
     "legendFormat": "Active"
    },
    {
     "expr": "count by(instance) (monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type!=\"group\"} == 2)",
     "legendFormat": "Pending"
    },
    {
     "expr": "count by(instance) (monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type!=\"group\"} == 0)",
     "legendFormat": "Inactive"
    },
    {
     "expr": "count by(instance) (monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type!=\"group\"} == 3)",
     "legendFormat": "Under Maintenance"
    }
   ]
  },
  {
   "title": "Unhealthy Services",
   "type": "stat",
   "description": "This Panel lists Services that are in inactive state",
   "gridPos": { "h": 28, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type!=\"group\"} == 0",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  },
  {
   "title": "Pending Services",
   "type": "stat",
   "description": "This Panel lists Services that are in pending state",
   "gridPos": { "h": 28, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type!=\"group\"} == 2",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  },
  {
   "title": "Services in Maintenance",
   "type": "stat",
   "description": "This Panel lists Services that are currently under Maintenance\n",
   "gridPos": { "h": 28, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type!=\"group\"} == 3",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  },
  {
   "title": "Certificate Validity Days",
   "type": "stat",
   "description": "This panel shows all http services and the remaining days after the certificate needs to be renewed",
   "gridPos": { "h": 24, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(monitor_cert_days_remaining{instance=\"$Instance\", monitor_type=\"http\", job=\"$job\"} < 65)",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  },
  {
   "title": "Monitors by Type",
   "type": "stat",
   "gridPos": { "h": 24, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(count by(monitor_type) (monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type!=\"group\"}))",
     "legendFormat": "{{monitor_type}}"
    }
   ]
  },
  {
   "title": "Groups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Group Status",
     "type": "stat",
     "gridPos": { "h": 15, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type=\"group\", monitor_name=~\"$groups\"}",
       "legendFormat": "{{monitor_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Details ($monitor_types based)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "monitor_types",
   "collapsed": true,
   "panels": [
    {
     "title": "Services",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count by(instance) (monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type=\"$monitor_types\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "count by(instance) (monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type=\"$monitor_types\"} == 1)",
       "legendFormat": "Active"
      },
      {
       "expr": "count by(instance) (monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type=\"$monitor_types\"} == 2)",
       "legendFormat": "Pending"
      },
      {
       "expr": "count by(instance) (monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type=\"$monitor_types\"} == 0)",
       "legendFormat": "Inactive"
      },
      {
       "expr": "count by(instance) (monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type=\"$monitor_types\"} == 3)",
       "legendFormat": "Under Maintenance"
      }
     ]
    },
    {
     "title": "Unhealthy Services",
     "type": "stat",
     "description": "This Panel lists Services that are in inactive state",
     "gridPos": { "h": 20, "w": 4, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type=\"$monitor_types\"} == 0",
       "legendFormat": "{{monitor_name}}"
      }
     ]
    },
    {
     "title": "Pending Services",
     "type": "stat",
     "description": "This Panel lists Services that are in pending state",
     "gridPos": { "h": 20, "w": 4, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type=\"$monitor_types\"} == 2",
       "legendFormat": "{{monitor_name}}"
      }
     ]
    },
    {
     "title": "Services in Maintenance",
     "type": "stat",
     "description": "This Panel lists Services that are currently under Maintenance\n",
     "gridPos": { "h": 20, "w": 4, "x": 20, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "monitor_status{instance=\"$Instance\", job=\"$job\", monitor_type=\"$monitor_types\"} == 3",
       "legendFormat": "{{monitor_name}}"
      }
     ]
    },
    {
     "title": "Response Times of all $monitor_types - Based Services",
     "type": "timeseries",
     "description": "This panel shows the different $monitor_types based services and their response times in the selected interval as well as their mean- and minimum response time.",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "monitor_response_time{monitor_type=\"$monitor_types\", instance=\"$Instance\", job=\"$job\"}",
       "legendFormat": "{{monitor_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeJS Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nodejs_version_info", "legendFormat": "{{version}}" }
     ]
    },
    {
     "title": "Event Loop Delay",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 2, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_min_seconds{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Min"
      },
      {
       "expr": "nodejs_eventloop_lag_mean_seconds{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Mean"
      },
      {
       "expr": "nodejs_eventloop_lag_max_seconds{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Node JS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 7, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nodejs_active_handles_total{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Active Handles"
      },
      {
       "expr": "nodejs_active_handles_total{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Active Handles Total"
      },
      {
       "expr": "nodejs_active_requests_total{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Active Requets Total"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "gridPos": { "h": 4, "w": 11, "x": 13, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Resident Memory"
      },
      {
       "expr": "process_virtual_memory_bytes{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Virtual Memory"
      },
      {
       "expr": "nodejs_external_memory_bytes{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "External Memory"
      },
      {
       "expr": "process_heap_bytes{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Heap"
      },
      {
       "expr": "nodejs_heap_size_total_bytes{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Heap Total"
      },
      {
       "expr": "nodejs_heap_size_used_bytes{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Heap Used"
      }
     ]
    },
    {
     "title": "Process FDS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 7, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_open_fds{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Open File Descriptors"
      },
      {
       "expr": "process_max_fds{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Max Open File Descriptors"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Resident Memory"
      },
      {
       "expr": "nodejs_external_memory_bytes{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "External Memory"
      },
      {
       "expr": "process_heap_bytes{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Heap"
      },
      {
       "expr": "nodejs_heap_size_total_bytes{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Heap Total"
      },
      {
       "expr": "nodejs_heap_size_used_bytes{job=\"$job\", instance=\"$Instance\"}",
       "legendFormat": "Heap Used"
      }
     ]
    }
   ]
  }
 ]
}