---
apiVersion: postgresql.cnpg.io/v1
kind: Subscription
metadata:
  name: zitadel-green-sub
  namespace: authentication
spec:
  cluster:
    name: zitadel-green
  dbname: zitadel
  name: zitadel_green_sub
  publicationName: zitadel_green_pub
  externalClusterName: zitadel
  subscriptionReclaimPolicy: delete
