---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - access-policy-cronjob.yaml
  - certificate.yaml
  - externalsecret.yaml
  - helmrelease.yaml
  - httproute.yaml
  - networkpolicy.yaml

configMapGenerator:
  - name: zitadel-access-policy
    files:
      - access-policy.yaml
      - reconcile-access-policy.rb

generatorOptions:
  disableNameSuffixHash: true
