---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-redis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: n8n-redis
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: redis-auth
        property: n8n_password
