---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name dockerhub-credentials
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "database,external-secrets,home,monitoring,network,openebs-system,reflector,storage,system-upgrade"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "database,external-secrets,home,monitoring,network,openebs-system,reflector,storage,system-upgrade"
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  dataFrom:
    - extract:
        key: dockerhub
