---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-cinc-registry
  namespace: storage
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rustfs-cinc-registry
    template:
      engineVersion: v2
      data:
        RUSTFS_CINC_OCI_ACCESS_KEY: "{{ .RUSTFS_CINC_OCI_ACCESS_KEY }}"
        RUSTFS_CINC_OCI_SECRET_KEY: "{{ .RUSTFS_CINC_OCI_SECRET_KEY }}"
        RUSTFS_CINC_ARTIFACTS_ACCESS_KEY: "{{ .RUSTFS_CINC_ARTIFACTS_ACCESS_KEY }}"
        RUSTFS_CINC_ARTIFACTS_SECRET_KEY: "{{ .RUSTFS_CINC_ARTIFACTS_SECRET_KEY }}"
        RUSTFS_CINC_BACKUP_ACCESS_KEY: "{{ .RUSTFS_CINC_BACKUP_ACCESS_KEY }}"
        RUSTFS_CINC_BACKUP_SECRET_KEY: "{{ .RUSTFS_CINC_BACKUP_SECRET_KEY }}"
  data:
  - secretKey: RUSTFS_CINC_OCI_ACCESS_KEY
    remoteRef:
      key: rustfs-cinc-registry-oci
      property: username
  - secretKey: RUSTFS_CINC_OCI_SECRET_KEY
    remoteRef:
      key: rustfs-cinc-registry-oci
      property: password
  - secretKey: RUSTFS_CINC_ARTIFACTS_ACCESS_KEY
    remoteRef:
      key: rustfs-cinc-registry-artifacts
      property: username
  - secretKey: RUSTFS_CINC_ARTIFACTS_SECRET_KEY
    remoteRef:
      key: rustfs-cinc-registry-artifacts
      property: password
  - secretKey: RUSTFS_CINC_BACKUP_ACCESS_KEY
    remoteRef:
      key: rustfs-cnpg-cinc-registry
      property: username
  - secretKey: RUSTFS_CINC_BACKUP_SECRET_KEY
    remoteRef:
      key: rustfs-cnpg-cinc-registry
      property: password
