---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi-release-announcer
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: uninstall
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      imagePullSecrets:
        - name: ghcr-credentials

    controllers:
      app:
        containers:
          app:
            image:
              repository: ghcr.io/damacus/unifi-release-announcer
              tag: 0.2.12@sha256:60607a5831915e24f55eb7dd9cf956172db5567bf2dd49308317f3aa1e0f6fff
            env:
              - name: TAGS
                value: "unifi-drive,unifi-network,unifi-protect"
              - name: DISCORD_BOT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: unifi-release-announcer
                    key: DISCORD_BOT_TOKEN
              - name: DISCORD_CHANNEL_ID
                valueFrom:
                  secretKeyRef:
                    name: unifi-release-announcer
                    key: DISCORD_CHANNEL_ID
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              capabilities:
                drop: ["ALL"]
              seccompProfile:
                type: RuntimeDefault
            resources:
              requests:
                cpu: 10m
                memory: 100M
              limits:
                cpu: 1000m
                memory: 100M

    persistence:
      cache:
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /cache
        size: 10m
