---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: paperless-localdata-restore
  namespace: home-automation
spec:
  paused: true
  trigger:
    manual: restore-once
  restic:
    repository: rustfs-paperless
    destinationPVC: paperless-localdata-restore
    copyMethod: Direct
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    capacity: 6Gi
    cacheCapacity: 1Gi
    cacheStorageClassName: openebs-hostpath
    moverSecurityContext:
      runAsUser: 1030
      runAsGroup: 1030
      fsGroup: 1030
