---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name med-tracker-canary
  namespace: home
spec:
  imagePullSecrets:
    - name: ghcr-credentials
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 18
  instances: 1
  primaryUpdateStrategy: unsupervised
  managed:
    roles:
      - name: med_tracker_owner
        ensure: present
        login: false
        superuser: false
        bypassrls: false
      - name: med_tracker_app
        ensure: present
        login: false
        superuser: false
        bypassrls: false
      - name: med-tracker
        ensure: present
        login: true
        superuser: false
        bypassrls: false
        inRoles:
          - med_tracker_owner
          - med_tracker_app
        passwordSecret:
          name: med-tracker-canary-db
  storage:
    size: 5Gi
    storageClass: openebs-hostpath

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: med-tracker
      owner: med-tracker
      secret:
        name: med-tracker-canary-db
      postInitApplicationSQL:
        - CREATE ROLE med_tracker_owner NOLOGIN NOSUPERUSER NOBYPASSRLS
        - CREATE ROLE med_tracker_app NOLOGIN NOSUPERUSER NOBYPASSRLS
        - GRANT med_tracker_owner, med_tracker_app TO "med-tracker"
        - ALTER DATABASE "med-tracker" OWNER TO med_tracker_owner
        - ALTER SCHEMA public OWNER TO med_tracker_owner

  enableSuperuserAccess: false

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 128MB

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 2000m
      memory: 512Mi
