---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: med-tracker-canary-db
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: med-tracker-canary-db
    template:
      data:
        username: "med-tracker"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: med-tracker-canary-db
