---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name authentik-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .BOOTSTRAP_EMAIL }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .BOOTSTRAP_PASSWORD }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .BOOTSTRAP_TOKEN }}"
        AUTHENTIK_SECRET_KEY: "{{ .SECRET_KEY }}"
  dataFrom:
    - extract:
        key: authentik
