---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
  namespace: authentication
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oauth2-proxy
    template:
      engineVersion: v2
      data:
        OAUTH2_PROXY_CLIENT_ID: "{{ .client_id }}"
        OAUTH2_PROXY_CLIENT_SECRET: "{{ .client_secret }}"
        OAUTH2_PROXY_COOKIE_SECRET: "{{ .cookie_secret }}"
  dataFrom:
    - extract:
        key: zitadel-oauth2-proxy-oidc
