---
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: storage
spec:
  backupTargetURL: s3://longhorn@us-east-1/
  credentialSecret: rustfs-longhorn
  pollInterval: 5m0s
