---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-r2
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: longhorn-r2
  dataFrom:
    - extract:
        key: longhorn-r2
