---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-longhorn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rustfs-longhorn
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .username }}"
        AWS_SECRET_ACCESS_KEY: "{{ .password }}"
        AWS_ENDPOINTS: http://rustfs.storage.svc.cluster.local:9000
  data:
    - secretKey: username
      remoteRef:
        key: rustfs-longhorn
        property: username
    - secretKey: password
      remoteRef:
        key: rustfs-longhorn
        property: password
