---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backuptarget.yaml
  - ./externalsecret.yaml
  - ./HelmRelease.yaml
  - ./httproute.yaml
  - ./PrometheusRule.yaml
  - ./servicemonitor.yaml
