---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant-traefik-internal
  annotations:
    external-dns.alpha.kubernetes.io/target: "traefik-int.ironstone.casa"
    gatus.home-operations.com/endpoint: |
      name: Home Assistant (Internal)
      group: cluster
      url: https://home-assistant.ironstone.casa/
      conditions:
        - "[STATUS] == 200"
        - "[RESPONSE_TIME] < 3000"
spec:
  hostnames:
    - hass.ironstone.casa
    - home-assistant.ironstone.casa
  parentRefs:
    - name: traefik-internal
      namespace: network
      sectionName: websecure
  rules:
    - backendRefs:
        - kind: Service
          name: home-assistant
          port: 8123
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant-traefik-external
  annotations:
    external-dns.alpha.kubernetes.io/target: "traefik-ext.damacus.io"
    gatus.home-operations.com/enabled: "false"
spec:
  hostnames:
    - hass.damacus.io
    - home-assistant.damacus.io
  parentRefs:
    - name: traefik-internal
      namespace: network
      sectionName: websecure
  rules:
    - backendRefs:
        - kind: Service
          name: home-assistant
          port: 8123
      matches:
        - path:
            type: PathPrefix
            value: /
