---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: northbot
  namespace: dev
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
