---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: northbot
  namespace: dev
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
