apiVersion: v1
kind: Secret
metadata:
  name: gatus-secret
stringData:
  GATUS_WATCHDOG_TOKEN: ENC[AES256_GCM,data:u23GqcE3WgfpZXjvuZeeCBRDkuAEZmEhobuB0mo5BUgdFyGflzj8mc/iWMrdf98GvL5CzHOtZyRgNppEPxGI2w==,iv:adbfXK7Eott6USEg9hv5wOp+Cu7jfyLIym38yjdDRzI=,tag:aETN3794NIEhOfHnOUiBjg==,type:str]
sops:
  age:
    - recipient: age1hc5sdag42jn8z9gw87k67rrnz4qx7m6g7qnjmy9vefd6dxw2xc2q8jnjma
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYVN6RExXNDZaaGUxTWln
        Mk5xNVZkZkxhZzNQa1ZsbklGOHYzdXZqZkNFCjNybzRvais4R0hpR2k0K3U2UkJT
        M2wwMlNVM2RlMHNlZDBySC9SWXhra1kKLS0tIHlNQ2dLTGxkd0pZNVZxTTVDdllo
        QXFpeUFjUDMzTGU0ZGdMb0FuYkhxYTAKgbG8NEi1B3nudkikiwcrgi86YbRm+Xa1
        pMNlP70yJaPmMGV6J8aC//QGPns0WqtS9vfI+ySm4m2XnWwC98dxew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T14:37:05Z"
  mac: ENC[AES256_GCM,data:NIy8IIFXxwJ7B5vuayN9VuyET31fmRBZNgJGRlbBuxCRYScMYPkCaCspi7aIvj4/fCu6iA8DBRR5mrtnK3Ag4ydEK5BT4JQrqP9rxYxtiTRVzblaY+M0O0RAUQg3QyBe5BrLxWpuERTNxPVzbzgUg92gtkC/5RwQA73eqkd+oYQ=,iv:IrBFObDNH3qOTjakXByQt0h/EbnMITX/hDrRnLJzEwA=,tag:bcPRSsz+GXlVkR0wLmoU8g==,type:str]
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.12.1
