---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: codeserver-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: codeserver-auth
    template:
      engineVersion: v2
  data:
    - secretKey: PASSWORD
      remoteRef:
        key: codeserver-auth
        property: PASSWORD
