---
apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: code
spec:
  target:
    service: code
    port: 8080
  rules:
    - hosts:
        - code.ironstone.casa
  scalingMetric:
    concurrency:
      targetValue: 10
