---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: code
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/controller: code
      app.kubernetes.io/instance: code
      app.kubernetes.io/name: code
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: network
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - port: 8080
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: keda
      ports:
        - port: 8080
          protocol: TCP
