---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    imagePullSecrets:
      - name: dockerhub-credentials

    preUpgradeHook:
      imagePullSecrets:
        - name: dockerhub-credentials

    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
        rawfile:
          enabled: false
      replicated:
        mayastor:
          enabled: false

    localpv-provisioner:
      imagePullSecrets:
        - name: dockerhub-credentials
      enabled: true
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: false
        basePath: /var/openebs/local

    loki:
      imagePullSecrets:
        - name: dockerhub-credentials
      serviceAccount:
        imagePullSecrets:
          - name: dockerhub-credentials

    alloy:
      global:
        image:
          pullSecrets:
            - name: dockerhub-credentials
